<?php

/*
|--------------------------------------------------------------------------
| Module Routes
|--------------------------------------------------------------------------
|
| Here is where all module routes generated by CRUD Generator.
*/

require app_path('Http/Routes/clients_routes.php');
require app_path('Http/Routes/clients_admins_routes.php');
require app_path('Http/Routes/logs_email_routes.php');
require app_path('Http/Routes/hosts_routes.php');
require app_path('Http/Routes/hosts_checks_routes.php');
require app_path('Http/Routes/hosts_history_routes.php');
require app_path('Http/Routes/hosts_admins_routes.php');
require app_path('Http/Routes/labels_routes.php');
require app_path('Http/Routes/license_categories_routes.php');
require app_path('Http/Routes/notification_templates_routes.php');
require app_path('Http/Routes/projects_routes.php');
require app_path('Http/Routes/projects_admins_routes.php');
require app_path('Http/Routes/logs_sms_routes.php');
require app_path('Http/Routes/suppliers_routes.php');
require app_path('Http/Routes/asset_categories_routes.php');
require app_path('Http/Routes/contacts_routes.php');
require app_path('Http/Routes/credentials_routes.php');
require app_path('Http/Routes/issues_routes.php');
require app_path('Http/Routes/tickets_routes.php');
require app_path('Http/Routes/tickets_people_routes.php');
require app_path('Http/Routes/tickets_replies_routes.php');
require app_path('Http/Routes/tickets_rules_routes.php');
require app_path('Http/Routes/comments_routes.php');
require app_path('Http/Routes/lcenses_assets_routes.php');
require app_path('Http/Routes/files_routes.php');
require app_path('Http/Routes/assets_routes.php');
require app_path('Http/Routes/licenses_routes.php');
require app_path('Http/Routes/devices_categories_routes.php');
require app_path('Http/Routes/devices_routes.php');
