<?php

/*
|--------------------------------------------------------------------------
| Assets Routes
|--------------------------------------------------------------------------
|
| Here is where all assets routes generated by CRUD Generator.
*/

LucyRoute::get('assets', 'Modules\AssetController@index', 'assets.view');
LucyRoute::get('assets/datatables', 'Modules\AssetController@datatables', 'assets.view');
LucyRoute::get('assets/create', 'Modules\AssetController@create', 'assets.create');
LucyRoute::post('assets', 'Modules\AssetController@store', 'assets.create');
LucyRoute::get('assets/{id}/edit', 'Modules\AssetController@edit', 'assets.edit');
LucyRoute::put('assets/{id}', 'Modules\AssetController@update', 'assets.edit');
LucyRoute::get('assets/{id}', 'Modules\AssetController@show', 'assets.view');
LucyRoute::delete('assets/{id}', 'Modules\AssetController@destroy', 'assets.delete');
