<?php

/*
|--------------------------------------------------------------------------
| AssetCategories Routes
|--------------------------------------------------------------------------
|
| Here is where all assetcategories routes generated by CRUD Generator.
*/

LucyRoute::get('asset_categories', 'Modules\AssetCategoryController@index', 'assetcategories.view');
LucyRoute::get('asset_categories/datatables', 'Modules\AssetCategoryController@datatables', 'assetcategories.view');
LucyRoute::get('asset_categories/create', 'Modules\AssetCategoryController@create', 'assetcategories.create');
LucyRoute::post('asset_categories', 'Modules\AssetCategoryController@store', 'assetcategories.create');
LucyRoute::get('asset_categories/{id}/edit', 'Modules\AssetCategoryController@edit', 'assetcategories.edit');
LucyRoute::put('asset_categories/{id}', 'Modules\AssetCategoryController@update', 'assetcategories.edit');
LucyRoute::get('asset_categories/{id}', 'Modules\AssetCategoryController@show', 'assetcategories.view');
LucyRoute::delete('asset_categories/{id}', 'Modules\AssetCategoryController@destroy', 'assetcategories.delete');
