<?php

/*
|--------------------------------------------------------------------------
| ClientsAdmins Routes
|--------------------------------------------------------------------------
|
| Here is where all clientsadmins routes generated by CRUD Generator.
*/

LucyRoute::get('clients_admins', 'Modules\ClientsAdminController@index', 'clientsadmins.view');
LucyRoute::get('clients_admins/datatables', 'Modules\ClientsAdminController@datatables', 'clientsadmins.view');
LucyRoute::get('clients_admins/create', 'Modules\ClientsAdminController@create', 'clientsadmins.create');
LucyRoute::post('clients_admins', 'Modules\ClientsAdminController@store', 'clientsadmins.create');
LucyRoute::get('clients_admins/{id}/edit', 'Modules\ClientsAdminController@edit', 'clientsadmins.edit');
LucyRoute::put('clients_admins/{id}', 'Modules\ClientsAdminController@update', 'clientsadmins.edit');
LucyRoute::get('clients_admins/{id}', 'Modules\ClientsAdminController@show', 'clientsadmins.view');
LucyRoute::delete('clients_admins/{id}', 'Modules\ClientsAdminController@destroy', 'clientsadmins.delete');
