<?php

/*
|--------------------------------------------------------------------------
| Clients Routes
|--------------------------------------------------------------------------
|
| Here is where all clients routes generated by CRUD Generator.
*/

LucyRoute::get('clients', 'Modules\ClientController@index', 'clients.view');
LucyRoute::get('clients/datatables', 'Modules\ClientController@datatables', 'clients.view');
LucyRoute::get('clients/create', 'Modules\ClientController@create', 'clients.create');
LucyRoute::post('clients', 'Modules\ClientController@store', 'clients.create');
LucyRoute::get('clients/{id}/edit', 'Modules\ClientController@edit', 'clients.edit');
LucyRoute::put('clients/{id}', 'Modules\ClientController@update', 'clients.edit');
LucyRoute::get('clients/{id}', 'Modules\ClientController@show', 'clients.view');
LucyRoute::delete('clients/{id}', 'Modules\ClientController@destroy', 'clients.delete');
LucyRoute::post('clients/{id}/attach', 'Modules\ClientController@attachUser', 'clients.attachUser');
LucyRoute::delete('clients/{client}/detach/{id}', 'Modules\ClientController@detachUser', 'clients.delete');
LucyRoute::get('clients/{id}/assets', 'Modules\ClientController@datatablesAssets', 'clients.view');