<?php

/*
|--------------------------------------------------------------------------
| Comments Routes
|--------------------------------------------------------------------------
|
| Here is where all comments routes generated by CRUD Generator.
*/

LucyRoute::get('comments', 'Modules\CommentController@index', 'comments.view');
LucyRoute::get('comments/datatables', 'Modules\CommentController@datatables', 'comments.view');
LucyRoute::get('comments/create', 'Modules\CommentController@create', 'comments.create');
LucyRoute::post('comments', 'Modules\CommentController@store', 'comments.create');
LucyRoute::get('comments/{id}/edit', 'Modules\CommentController@edit', 'comments.edit');
LucyRoute::put('comments/{id}', 'Modules\CommentController@update', 'comments.edit');
LucyRoute::get('comments/{id}', 'Modules\CommentController@show', 'comments.view');
LucyRoute::delete('comments/{id}', 'Modules\CommentController@destroy', 'comments.delete');
