<?php

/*
|--------------------------------------------------------------------------
| Contacts Routes
|--------------------------------------------------------------------------
|
| Here is where all contacts routes generated by CRUD Generator.
*/

LucyRoute::get('contacts', 'Modules\ContactController@index', 'contacts.view');
LucyRoute::get('contacts/datatables', 'Modules\ContactController@datatables', 'contacts.view');
LucyRoute::get('contacts/create', 'Modules\ContactController@create', 'contacts.create');
LucyRoute::post('contacts', 'Modules\ContactController@store', 'contacts.create');
LucyRoute::get('contacts/{id}/edit', 'Modules\ContactController@edit', 'contacts.edit');
LucyRoute::put('contacts/{id}', 'Modules\ContactController@update', 'contacts.edit');
LucyRoute::get('contacts/{id}', 'Modules\ContactController@show', 'contacts.view');
LucyRoute::delete('contacts/{id}', 'Modules\ContactController@destroy', 'contacts.delete');
