<?php

/*
|--------------------------------------------------------------------------
| Credentials Routes
|--------------------------------------------------------------------------
|
| Here is where all credentials routes generated by CRUD Generator.
*/

LucyRoute::get('credentials', 'Modules\CredentialController@index', 'credentials.view');
LucyRoute::get('credentials/datatables', 'Modules\CredentialController@datatables', 'credentials.view');
LucyRoute::get('credentials/create', 'Modules\CredentialController@create', 'credentials.create');
LucyRoute::post('credentials', 'Modules\CredentialController@store', 'credentials.create');
LucyRoute::get('credentials/{id}/edit', 'Modules\CredentialController@edit', 'credentials.edit');
LucyRoute::put('credentials/{id}', 'Modules\CredentialController@update', 'credentials.edit');
LucyRoute::get('credentials/{id}', 'Modules\CredentialController@show', 'credentials.view');
LucyRoute::delete('credentials/{id}', 'Modules\CredentialController@destroy', 'credentials.delete');
