<?php

/*
|--------------------------------------------------------------------------
| DevicesCategories Routes
|--------------------------------------------------------------------------
|
| Here is where all devicescategories routes generated by CRUD Generator.
*/

LucyRoute::get('devices_categories', 'Modules\DeviceCategoryController@index', 'devicescategories.view');
LucyRoute::get('devices_categories/datatables', 'Modules\DeviceCategoryController@datatables', 'devicescategories.view');
LucyRoute::get('devices_categories/create', 'Modules\DeviceCategoryController@create', 'devicescategories.create');
LucyRoute::post('devices_categories', 'Modules\DeviceCategoryController@store', 'devicescategories.create');
LucyRoute::get('devices_categories/{id}/edit', 'Modules\DeviceCategoryController@edit', 'devicescategories.edit');
LucyRoute::put('devices_categories/{id}', 'Modules\DeviceCategoryController@update', 'devicescategories.edit');
LucyRoute::get('devices_categories/{id}', 'Modules\DeviceCategoryController@show', 'devicescategories.view');
LucyRoute::delete('devices_categories/{id}', 'Modules\DeviceCategoryController@destroy', 'devicescategories.delete');
