<?php

/*
|--------------------------------------------------------------------------
| Devices Routes
|--------------------------------------------------------------------------
|
| Here is where all devices routes generated by CRUD Generator.
*/

LucyRoute::get('devices', 'Modules\DeviceController@index', 'devices.view');
LucyRoute::get('devices/datatables', 'Modules\DeviceController@datatables', 'devices.view');
LucyRoute::get('devices/create', 'Modules\DeviceController@create', 'devices.create');
LucyRoute::post('devices', 'Modules\DeviceController@store', 'devices.create');
LucyRoute::get('devices/{id}/edit', 'Modules\DeviceController@edit', 'devices.edit');
LucyRoute::put('devices/{id}', 'Modules\DeviceController@update', 'devices.edit');
LucyRoute::get('devices/{id}', 'Modules\DeviceController@show', 'devices.view');
LucyRoute::delete('devices/{id}', 'Modules\DeviceController@destroy', 'devices.delete');
