<?php

/*
|--------------------------------------------------------------------------
| Files Routes
|--------------------------------------------------------------------------
|
| Here is where all files routes generated by CRUD Generator.
*/

LucyRoute::get('files', 'Modules\FileController@index', 'files.view');
LucyRoute::get('files/datatables', 'Modules\FileController@datatables', 'files.view');
LucyRoute::get('files/create', 'Modules\FileController@create', 'files.create');
LucyRoute::post('files', 'Modules\FileController@store', 'files.create');
LucyRoute::get('files/{id}/edit', 'Modules\FileController@edit', 'files.edit');
LucyRoute::put('files/{id}', 'Modules\FileController@update', 'files.edit');
LucyRoute::get('files/{id}', 'Modules\FileController@show', 'files.view');
LucyRoute::delete('files/{id}', 'Modules\FileController@destroy', 'files.delete');
