<?php

/*
|--------------------------------------------------------------------------
| Hosts Routes
|--------------------------------------------------------------------------
|
| Here is where all hosts routes generated by CRUD Generator.
*/

LucyRoute::get('hosts', 'Modules\HostController@index', 'hosts.view');
LucyRoute::get('hosts/datatables', 'Modules\HostController@datatables', 'hosts.view');
LucyRoute::get('hosts/create', 'Modules\HostController@create', 'hosts.create');
LucyRoute::post('hosts', 'Modules\HostController@store', 'hosts.create');
LucyRoute::get('hosts/{id}/edit', 'Modules\HostController@edit', 'hosts.edit');
LucyRoute::put('hosts/{id}', 'Modules\HostController@update', 'hosts.edit');
LucyRoute::get('hosts/{id}', 'Modules\HostController@show', 'hosts.view');
LucyRoute::delete('hosts/{id}', 'Modules\HostController@destroy', 'hosts.delete');
