<?php

/*
|--------------------------------------------------------------------------
| HostsAdmins Routes
|--------------------------------------------------------------------------
|
| Here is where all hostsadmins routes generated by CRUD Generator.
*/

LucyRoute::get('hosts_admins', 'Modules\HostsAdminController@index', 'hostsadmins.view');
LucyRoute::get('hosts_admins/datatables', 'Modules\HostsAdminController@datatables', 'hostsadmins.view');
LucyRoute::get('hosts_admins/create', 'Modules\HostsAdminController@create', 'hostsadmins.create');
LucyRoute::post('hosts_admins', 'Modules\HostsAdminController@store', 'hostsadmins.create');
LucyRoute::get('hosts_admins/{id}/edit', 'Modules\HostsAdminController@edit', 'hostsadmins.edit');
LucyRoute::put('hosts_admins/{id}', 'Modules\HostsAdminController@update', 'hostsadmins.edit');
LucyRoute::get('hosts_admins/{id}', 'Modules\HostsAdminController@show', 'hostsadmins.view');
LucyRoute::delete('hosts_admins/{id}', 'Modules\HostsAdminController@destroy', 'hostsadmins.delete');
