<?php

/*
|--------------------------------------------------------------------------
| HostsChecks Routes
|--------------------------------------------------------------------------
|
| Here is where all hostschecks routes generated by CRUD Generator.
*/

LucyRoute::get('hosts_checks', 'Modules\HostsCheckController@index', 'hostschecks.view');
LucyRoute::get('hosts_checks/datatables', 'Modules\HostsCheckController@datatables', 'hostschecks.view');
LucyRoute::get('hosts_checks/create', 'Modules\HostsCheckController@create', 'hostschecks.create');
LucyRoute::post('hosts_checks', 'Modules\HostsCheckController@store', 'hostschecks.create');
LucyRoute::get('hosts_checks/{id}/edit', 'Modules\HostsCheckController@edit', 'hostschecks.edit');
LucyRoute::put('hosts_checks/{id}', 'Modules\HostsCheckController@update', 'hostschecks.edit');
LucyRoute::get('hosts_checks/{id}', 'Modules\HostsCheckController@show', 'hostschecks.view');
LucyRoute::delete('hosts_checks/{id}', 'Modules\HostsCheckController@destroy', 'hostschecks.delete');
