<?php

/*
|--------------------------------------------------------------------------
| HostsHistory Routes
|--------------------------------------------------------------------------
|
| Here is where all hostshistory routes generated by CRUD Generator.
*/

LucyRoute::get('hosts_history', 'Modules\HostsHistoryController@index', 'hostshistory.view');
LucyRoute::get('hosts_history/datatables', 'Modules\HostsHistoryController@datatables', 'hostshistory.view');
LucyRoute::get('hosts_history/create', 'Modules\HostsHistoryController@create', 'hostshistory.create');
LucyRoute::post('hosts_history', 'Modules\HostsHistoryController@store', 'hostshistory.create');
LucyRoute::get('hosts_history/{id}/edit', 'Modules\HostsHistoryController@edit', 'hostshistory.edit');
LucyRoute::put('hosts_history/{id}', 'Modules\HostsHistoryController@update', 'hostshistory.edit');
LucyRoute::get('hosts_history/{id}', 'Modules\HostsHistoryController@show', 'hostshistory.view');
LucyRoute::delete('hosts_history/{id}', 'Modules\HostsHistoryController@destroy', 'hostshistory.delete');
