<?php

/*
|--------------------------------------------------------------------------
| Issues Routes
|--------------------------------------------------------------------------
|
| Here is where all issues routes generated by CRUD Generator.
*/

LucyRoute::get('issues', 'Modules\IssueController@index', 'issues.view');
LucyRoute::get('issues/datatables', 'Modules\IssueController@datatables', 'issues.view');
LucyRoute::get('issues/create', 'Modules\IssueController@create', 'issues.create');
LucyRoute::post('issues', 'Modules\IssueController@store', 'issues.create');
LucyRoute::get('issues/{id}/edit', 'Modules\IssueController@edit', 'issues.edit');
LucyRoute::put('issues/{id}', 'Modules\IssueController@update', 'issues.edit');
LucyRoute::get('issues/{id}', 'Modules\IssueController@show', 'issues.view');
LucyRoute::delete('issues/{id}', 'Modules\IssueController@destroy', 'issues.delete');
