<?php

/*
|--------------------------------------------------------------------------
| Labels Routes
|--------------------------------------------------------------------------
|
| Here is where all labels routes generated by CRUD Generator.
*/

LucyRoute::get('labels', 'Modules\LabelController@index', 'labels.view');
LucyRoute::get('labels/datatables', 'Modules\LabelController@datatables', 'labels.view');
LucyRoute::get('labels/create', 'Modules\LabelController@create', 'labels.create');
LucyRoute::post('labels', 'Modules\LabelController@store', 'labels.create');
LucyRoute::get('labels/{id}/edit', 'Modules\LabelController@edit', 'labels.edit');
LucyRoute::put('labels/{id}', 'Modules\LabelController@update', 'labels.edit');
LucyRoute::get('labels/{id}', 'Modules\LabelController@show', 'labels.view');
LucyRoute::delete('labels/{id}', 'Modules\LabelController@destroy', 'labels.delete');
