<?php

/*
|--------------------------------------------------------------------------
| LcensesAssets Routes
|--------------------------------------------------------------------------
|
| Here is where all lcensesassets routes generated by CRUD Generator.
*/

LucyRoute::get('lcenses_assets', 'Modules\IcensesAssetController@index', 'lcensesassets.view');
LucyRoute::get('lcenses_assets/datatables', 'Modules\IcensesAssetController@datatables', 'lcensesassets.view');
LucyRoute::get('lcenses_assets/create', 'Modules\IcensesAssetController@create', 'lcensesassets.create');
LucyRoute::post('lcenses_assets', 'Modules\IcensesAssetController@store', 'lcensesassets.create');
LucyRoute::get('lcenses_assets/{id}/edit', 'Modules\IcensesAssetController@edit', 'lcensesassets.edit');
LucyRoute::put('lcenses_assets/{id}', 'Modules\IcensesAssetController@update', 'lcensesassets.edit');
LucyRoute::get('lcenses_assets/{id}', 'Modules\IcensesAssetController@show', 'lcensesassets.view');
LucyRoute::delete('lcenses_assets/{id}', 'Modules\IcensesAssetController@destroy', 'lcensesassets.delete');
