<?php

/*
|--------------------------------------------------------------------------
| LicenseCategories Routes
|--------------------------------------------------------------------------
|
| Here is where all licensecategories routes generated by CRUD Generator.
*/

LucyRoute::get('license_categories', 'Modules\LicenseCategoryController@index', 'licensecategories.view');
LucyRoute::get('license_categories/datatables', 'Modules\LicenseCategoryController@datatables', 'licensecategories.view');
LucyRoute::get('license_categories/create', 'Modules\LicenseCategoryController@create', 'licensecategories.create');
LucyRoute::post('license_categories', 'Modules\LicenseCategoryController@store', 'licensecategories.create');
LucyRoute::get('license_categories/{id}/edit', 'Modules\LicenseCategoryController@edit', 'licensecategories.edit');
LucyRoute::put('license_categories/{id}', 'Modules\LicenseCategoryController@update', 'licensecategories.edit');
LucyRoute::get('license_categories/{id}', 'Modules\LicenseCategoryController@show', 'licensecategories.view');
LucyRoute::delete('license_categories/{id}', 'Modules\LicenseCategoryController@destroy', 'licensecategories.delete');
