<?php

/*
|--------------------------------------------------------------------------
| LogsEmail Routes
|--------------------------------------------------------------------------
|
| Here is where all logsemail routes generated by CRUD Generator.
*/

LucyRoute::get('logs_email', 'Modules\LogsEmailController@index', 'logsemail.view');
LucyRoute::get('logs_email/datatables', 'Modules\LogsEmailController@datatables', 'logsemail.view');
LucyRoute::get('logs_email/create', 'Modules\LogsEmailController@create', 'logsemail.create');
LucyRoute::post('logs_email', 'Modules\LogsEmailController@store', 'logsemail.create');
LucyRoute::get('logs_email/{id}/edit', 'Modules\LogsEmailController@edit', 'logsemail.edit');
LucyRoute::put('logs_email/{id}', 'Modules\LogsEmailController@update', 'logsemail.edit');
LucyRoute::get('logs_email/{id}', 'Modules\LogsEmailController@show', 'logsemail.view');
LucyRoute::delete('logs_email/{id}', 'Modules\LogsEmailController@destroy', 'logsemail.delete');
