<?php

/*
|--------------------------------------------------------------------------
| Manufacturers Routes
|--------------------------------------------------------------------------
|
| Here is where all manufacturers routes generated by CRUD Generator.
*/

LucyRoute::get('manufacturers', 'Modules\ManufacturerController@index', 'manufacturers.view');
LucyRoute::get('manufacturers/datatables', 'Modules\ManufacturerController@datatables', 'manufacturers.view');
LucyRoute::get('manufacturers/create', 'Modules\ManufacturerController@create', 'manufacturers.create');
LucyRoute::post('manufacturers', 'Modules\ManufacturerController@store', 'manufacturers.create');
LucyRoute::get('manufacturers/{id}/edit', 'Modules\ManufacturerController@edit', 'manufacturers.edit');
LucyRoute::put('manufacturers/{id}', 'Modules\ManufacturerController@update', 'manufacturers.edit');
LucyRoute::get('manufacturers/{id}', 'Modules\ManufacturerController@show', 'manufacturers.view');
LucyRoute::delete('manufacturers/{id}', 'Modules\ManufacturerController@destroy', 'manufacturers.delete');
