<?php

/*
|--------------------------------------------------------------------------
| Models Routes
|--------------------------------------------------------------------------
|
| Here is where all models routes generated by CRUD Generator.
*/

LucyRoute::get('models', 'Modules\ModelController@index', 'models.view');
LucyRoute::get('models/datatables', 'Modules\ModelController@datatables', 'models.view');
LucyRoute::get('models/create', 'Modules\ModelController@create', 'models.create');
LucyRoute::post('models', 'Modules\ModelController@store', 'models.create');
LucyRoute::get('models/{id}/edit', 'Modules\ModelController@edit', 'models.edit');
LucyRoute::put('models/{id}', 'Modules\ModelController@update', 'models.edit');
LucyRoute::get('models/{id}', 'Modules\ModelController@show', 'models.view');
LucyRoute::delete('models/{id}', 'Modules\ModelController@destroy', 'models.delete');
