<?php

/*
|--------------------------------------------------------------------------
| Projects Routes
|--------------------------------------------------------------------------
|
| Here is where all projects routes generated by CRUD Generator.
*/

LucyRoute::get('projects', 'Modules\ProjectController@index', 'projects.view');
LucyRoute::get('projects/datatables', 'Modules\ProjectController@datatables', 'projects.view');
LucyRoute::get('projects/create', 'Modules\ProjectController@create', 'projects.create');
LucyRoute::post('projects', 'Modules\ProjectController@store', 'projects.create');
LucyRoute::get('projects/{id}/edit', 'Modules\ProjectController@edit', 'projects.edit');
LucyRoute::put('projects/{id}', 'Modules\ProjectController@update', 'projects.edit');
LucyRoute::get('projects/{id}', 'Modules\ProjectController@show', 'projects.view');
LucyRoute::delete('projects/{id}', 'Modules\ProjectController@destroy', 'projects.delete');
