<?php

/*
|--------------------------------------------------------------------------
| test Routes
|--------------------------------------------------------------------------
|
| Here is where all test routes generated by CRUD Generator.
*/

LucyRoute::get('test', 'Modules\TestController@index', 'test.view');
LucyRoute::get('test/datatables', 'Modules\TestController@datatables', 'test.view');
LucyRoute::get('test/create', 'Modules\TestController@create', 'test.create');
LucyRoute::post('test', 'Modules\TestController@store', 'test.create');
LucyRoute::get('test/{id}/edit', 'Modules\TestController@edit', 'test.edit');
LucyRoute::put('test/{id}', 'Modules\TestController@update', 'test.edit');
LucyRoute::get('test/{id}', 'Modules\TestController@show', 'test.view');
LucyRoute::delete('test/{id}', 'Modules\TestController@destroy', 'test.delete');
