<?php

/*
|--------------------------------------------------------------------------
| TicketsRules Routes
|--------------------------------------------------------------------------
|
| Here is where all ticketsrules routes generated by CRUD Generator.
*/

LucyRoute::get('tickets_rules', 'Modules\TicketsRuleController@index', 'ticketsrules.view');
LucyRoute::get('tickets_rules/datatables', 'Modules\TicketsRuleController@datatables', 'ticketsrules.view');
LucyRoute::get('tickets_rules/create', 'Modules\TicketsRuleController@create', 'ticketsrules.create');
LucyRoute::post('tickets_rules', 'Modules\TicketsRuleController@store', 'ticketsrules.create');
LucyRoute::get('tickets_rules/{id}/edit', 'Modules\TicketsRuleController@edit', 'ticketsrules.edit');
LucyRoute::put('tickets_rules/{id}', 'Modules\TicketsRuleController@update', 'ticketsrules.edit');
LucyRoute::get('tickets_rules/{id}', 'Modules\TicketsRuleController@show', 'ticketsrules.view');
LucyRoute::delete('tickets_rules/{id}', 'Modules\TicketsRuleController@destroy', 'ticketsrules.delete');
