<?php

/*
|--------------------------------------------------------------------------
| TicketsPeople Routes
|--------------------------------------------------------------------------
|
| Here is where all ticketspeople routes generated by CRUD Generator.
*/

LucyRoute::get('tickets_people', 'Modules\TicketsPersonController@index', 'ticketspeople.view');
LucyRoute::get('tickets_people/datatables', 'Modules\TicketsPersonController@datatables', 'ticketspeople.view');
LucyRoute::get('tickets_people/create', 'Modules\TicketsPersonController@create', 'ticketspeople.create');
LucyRoute::post('tickets_people', 'Modules\TicketsPersonController@store', 'ticketspeople.create');
LucyRoute::get('tickets_people/{id}/edit', 'Modules\TicketsPersonController@edit', 'ticketspeople.edit');
LucyRoute::put('tickets_people/{id}', 'Modules\TicketsPersonController@update', 'ticketspeople.edit');
LucyRoute::get('tickets_people/{id}', 'Modules\TicketsPersonController@show', 'ticketspeople.view');
LucyRoute::delete('tickets_people/{id}', 'Modules\TicketsPersonController@destroy', 'ticketspeople.delete');
