<?php

/*
|--------------------------------------------------------------------------
| TicketsReplies Routes
|--------------------------------------------------------------------------
|
| Here is where all ticketsreplies routes generated by CRUD Generator.
*/

LucyRoute::get('tickets_replies', 'Modules\TicketsReplyController@index', 'ticketsreplies.view');
LucyRoute::get('tickets_replies/datatables', 'Modules\TicketsReplyController@datatables', 'ticketsreplies.view');
LucyRoute::get('tickets_replies/create', 'Modules\TicketsReplyController@create', 'ticketsreplies.create');
LucyRoute::post('tickets_replies', 'Modules\TicketsReplyController@store', 'ticketsreplies.create');
LucyRoute::get('tickets_replies/{id}/edit', 'Modules\TicketsReplyController@edit', 'ticketsreplies.edit');
LucyRoute::put('tickets_replies/{id}', 'Modules\TicketsReplyController@update', 'ticketsreplies.edit');
LucyRoute::get('tickets_replies/{id}', 'Modules\TicketsReplyController@show', 'ticketsreplies.view');
LucyRoute::delete('tickets_replies/{id}', 'Modules\TicketsReplyController@destroy', 'ticketsreplies.delete');
